# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json yarn.lock* package-lock.json* ./

# Install dependencies
# Use npm ci if package-lock.json exists, fallback to npm install
RUN if [ -f package-lock.json ]; then npm ci --ignore-scripts; else npm install --ignore-scripts; fi

# Copy the rest of the app
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional, MCP server uses stdio, not network port)

# Command to run the server
CMD [ "npm", "start" ]
